from datetime import datetime

from topologiq.dzw.utils.augmented_nx_graph import AugmentedNxGraph
from topologiq.dzw.utils.coordinates import Coordinates

from logging import getLogger
console = getLogger(__name__)

NodeList = list[int]
EdgeList = list[tuple[int,int]]

class TikzWriter:
    AXES = ['X', 'Y', 'Z']

    STYLE = 'zx'
    ROTATION_X = 58
    ROTATION_Z = 112

    def __init__(self, nx_graph: AugmentedNxGraph, label : str = "circuit"):
        self.__label = label
        self.__nx_graph = nx_graph

    @staticmethod
    def find_axis(step: Coordinates):
        step = step.as_tuple()

        for index in range(3):
            if step[index] != 0:
                return TikzWriter.AXES[index]

        return "U"

    def write_frame(self, output,
        plain_cubes: set[int], plain_pipes: set[tuple[int,int]],
        faint_cubes: set[int], faint_pipes: set[tuple[int,int]]
    ):
        output.write(f"\t\\ZxGraph[style={TikzWriter.STYLE},rotationX={TikzWriter.ROTATION_X},rotationZ={TikzWriter.ROTATION_Z}]")
        output.write("{\n")

        for cube in self.__nx_graph.get_cubes():
            cube_type = self.__nx_graph.get_cube_kind(cube).get_type()
            cube_reach = self.__nx_graph.get_cube_kind(cube).get_reach().as_tuple()
            cube_plane = 'U'
            for index in range(3):
                if cube_reach[index] != 0:
                    cube_plane = TikzWriter.AXES[index]

            cube_position = self.__nx_graph.get_cube_position(cube)

            if cube in plain_cubes:
                cube_visibility = 'plain'
            elif cube in faint_cubes:
                cube_visibility = 'faint'
            else:
                cube_visibility = 'ghost'

            cube_label = self.__nx_graph.get_node(cube)
            if cube_label is None:
                cube_label = ''

            line = f"\t\t\\Node[visibility={cube_visibility}, type={cube_type}, plane={cube_plane}, label={cube_label}, identifier=N{cube}]"
            line += "{" + str(cube_position) + "}\n"

            output.write(line)

        for pipe in self.__nx_graph.get_pipes():
            (source_cube, target_cube) = pipe
            source_position = self.__nx_graph.get_cube_position(source_cube)
            target_position = self.__nx_graph.get_cube_position(target_cube)

            pipe_type = self.__nx_graph.get_pipe_type(source_cube, target_cube).name.lower()

            if pipe in plain_pipes:
                pipe_visibility = 'plain'
            elif pipe in faint_pipes:
                pipe_visibility = 'faint'
            else:
                pipe_visibility = 'ghost'

            line =  f"\t\t% pipe-info : {source_cube}-{target_cube}\n"
            line += f"\t\t\\Edge[visibility={pipe_visibility}, axis={TikzWriter.find_axis(target_position - source_position)}, type={pipe_type}]"
            line += "{N" + str(source_cube) + "}{N" + str(target_cube) + "}\n"

            output.write(line)

        output.write("\t}\n")

    def write_file(self, filename = None):
        if filename is None:
            filename = f"../../output/tikz/volumetric-zx-diagram-{self.__label}.tex"

        output = open(filename, "w")
        output.write("\\documentclass[tikz, preview, border=1pt]{standalone}\n")
        output.write("\\input{tikz-volumetric-zx-graph.tex}\n")
        output.write(f"% Generated by topologiq at {datetime.now().strftime("%I:%M:%S%p on %B %d, %Y")} \n")
        output.write("\\begin{document}\n")

        # TODO: add the root only on the first frame
        plain_cubes: set[int] = set()
        plain_pipes: set[tuple[int,int]] = set()

        faint_cubes: set[int] = set()
        faint_pipes: set[tuple[int,int]] = set()

        node_realisation_order = self.__nx_graph.get_node_realisation_order()
        edge_realisation_order = self.__nx_graph.get_edge_realisation_order()

        if len(node_realisation_order) > 0:
            root = node_realisation_order[0]
            plain_cubes.add( self.__nx_graph.get_cube(root) )
            self.write_frame(output, plain_cubes, plain_pipes, faint_cubes, faint_pipes)

        if len(edge_realisation_order) > 0:
            for next_edge in edge_realisation_order:
                faint_cubes.update(plain_cubes)
                faint_pipes.update(plain_pipes)
                plain_cubes.clear()
                plain_pipes.clear()
                (source, target) = next_edge
                source_cube = self.__nx_graph.get_cube(source)
                target_cube = self.__nx_graph.get_cube(target)
                plain_cubes.add(source_cube)
                plain_cubes.add(target_cube)
                current = source_cube
                extra_cubes = self.__nx_graph.get_edge_realisation(source, target)
                for extra_cube in extra_cubes:
                    plain_cubes.add(extra_cube)
                    pipe = (current, extra_cube) if current < extra_cube else (extra_cube, current)
                    plain_pipes.add( pipe )
                    current = extra_cube
                plain_cubes.add(target_cube)
                pipe = (current, target_cube) if current < target_cube else (target_cube, current)
                plain_pipes.add( pipe )
                output.write(f"\t% Edge  : {source}-{target} [{source_cube}-{target_cube}] : {extra_cubes}\n")
                output.write(f"\t% Cubes : {plain_cubes}\n")
                output.write(f"\t% Pipes : {plain_pipes}\n")
                self.write_frame(output, plain_cubes, plain_pipes, faint_cubes, faint_pipes)

        plain_cubes.update(self.__nx_graph.get_cubes())
        plain_pipes.update(self.__nx_graph.get_pipes())

        faint_cubes.clear()
        faint_pipes.clear()

        self.write_frame(output, plain_cubes, plain_pipes, faint_cubes, faint_pipes)

        output.write("\\end{document}\n")

        output.close()