from topologiq.utils.classes import SimpleDictGraph


steane: SimpleDictGraph = {
    "nodes": [
        (1, "X"),
        (2, "Z"),
        (3, "Z"),
        (4, "Z"),
        (5, "X"),
        (6, "X"),
        (7, "X"),
        (8, "O"),
        (9, "O"),
        (10, "O"),
        (11, "O"),
        (12, "O"),
        (13, "O"),
        (14, "O"),
    ],
    "edges": [
        ((1, 2), "SIMPLE"),
        ((1, 3), "SIMPLE"),
        ((1, 4), "SIMPLE"),
        ((5, 2), "SIMPLE"),
        ((5, 3), "SIMPLE"),
        ((6, 2), "SIMPLE"),
        ((6, 4), "SIMPLE"),
        ((7, 3), "SIMPLE"),
        ((7, 4), "SIMPLE"),
        ((8, 1), "SIMPLE"),
        ((9, 5), "SIMPLE"),
        ((10, 6), "SIMPLE"),
        ((11, 7), "SIMPLE"),
        ((2, 12), "SIMPLE"),
        ((3, 13), "SIMPLE"),
        ((4, 14), "SIMPLE"),
    ],
}

steane_obfs: SimpleDictGraph = {
    "nodes": [
        (1, "Z"),
        (2, "X"),
        (3, "X"),
        (4, "X"),
        (5, "Z"),
        (6, "Z"),
        (7, "Z"),
        (8, "X"),
        (9, "O"),
        (10, "O"),
        (11, "O"),
        (12, "O"),
        (13, "O"),
        (14, "O"),
        (15, "O"),
    ],
    "edges": [
        ((1, 2), "SIMPLE"),
        ((1, 3), "SIMPLE"),
        ((1, 4), "SIMPLE"),
        ((1, 9), "SIMPLE"),
        ((2, 5), "SIMPLE"),
        ((2, 10), "SIMPLE"),
        ((3, 6), "SIMPLE"),
        ((3, 11), "SIMPLE"),
        ((4, 7), "SIMPLE"),
        ((4, 12), "SIMPLE"),
        ((5, 8), "SIMPLE"),
        ((5, 13), "SIMPLE"),
        ((6, 8), "SIMPLE"),
        ((6, 14), "SIMPLE"),
        ((7, 8), "SIMPLE"),
        ((7, 15), "SIMPLE"),
    ],
}

hadamard_line: SimpleDictGraph = {
    "nodes": [
        (0, "Z"),
        (1, "X"),
        (2, "Z"),
        (3, "X"),
        (4, "Z"),
        (5, "X"),
    ],
    "edges": [
        ((0, 1), "HADAMARD"),
        ((1, 2), "HADAMARD"),
        ((2, 3), "HADAMARD"),
        ((3, 4), "HADAMARD"),
        ((4, 5), "HADAMARD"),
    ],
}

hadamard_bend: SimpleDictGraph = {
    "nodes": [
        (0, "Z"),
        (1, "X"),
        (2, "Z"),
        (3, "X"),
        (4, "Z"),
        (5, "X"),
    ],
    "edges": [
        ((0, 1), "HADAMARD"),
        ((0, 2), "HADAMARD"),
        ((0, 5), "HADAMARD"),
        ((3, 4), "HADAMARD"),
        ((4, 5), "HADAMARD"),
    ],
}

hadamards_mess: SimpleDictGraph = {
    "nodes": [
        (1, "X"),
        (2, "Z"),
        (3, "Z"),
        (4, "Z"),
        (5, "X"),
        (6, "X"),
        (7, "X"),
        (8, "O"),
        (9, "O"),
        (10, "O"),
        (11, "O"),
        (12, "O"),
        (13, "O"),
        (14, "O"),
    ],
    "edges": [
        ((1, 2), "HADAMARD"),
        ((1, 3), "SIMPLE"),
        ((1, 4), "SIMPLE"),
        ((5, 2), "HADAMARD"),
        ((5, 3), "SIMPLE"),
        ((6, 2), "SIMPLE"),
        ((6, 4), "HADAMARD"),
        ((7, 3), "HADAMARD"),
        ((7, 4), "HADAMARD"),
        ((8, 1), "SIMPLE"),
        ((9, 5), "SIMPLE"),
        ((10, 6), "SIMPLE"),
        ((11, 7), "SIMPLE"),
        ((2, 12), "SIMPLE"),
        ((3, 13), "SIMPLE"),
        ((4, 14), "SIMPLE"),
    ],
}
